### ISSUE TITLE
Allow non-string parameters

### ISSUE THREAD

**Issue by ranisalt** [simonepri/phc-format#1]
Most parameters for Argon2 (and probably most other algorithms) are not strings, such as cost values. That makes it cumbersome to supply parameters as strings if every single must be converted.

**Comment by simonepri** [comment]
Working on it right now.

**Comment by simonepri** [comment]
@ranisalt when deserializing should we convert strings back to numbers if we can?

**Comment by ranisalt** [comment]
I'm not sure, sometimes we want parameters like "keyid" which are digits but not exactly numbers, but I think JS can handle it.

**Comment by simonepri** [comment]
The keyid is not B64 encoded?

The only problem with parsing parameters can be a parameters like this:
`$b=0003`
But the ""[specs](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md#decimal-encoding)"" says that this is not a valid encoding.

**Comment by simonepri** [comment]
@ranisalt can we close this?

**Comment by ranisalt** [comment]
Your call. It fits my uses now :smile: thanks
