### ISSUE TITLE
Accept buffer params encoding with Base64

### ISSUE THREAD

**Issue by ranisalt** [simonepri/phc-format#2]
I'm trying to add [associated data](https://tools.ietf.org/html/draft-irtf-cfrg-argon2-03#page-4) param to node-argon2, but it's value is a binary buffer and should be [encoded to B64](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md#argon2-encoding) and @phc/format implements that.

It would be handful to handle parameters that are buffers (alongside strings) and encode them in B64, therefore I request this feature.

**Comment by simonepri** [comment]
@ranisalt sorry this slipped under my radar.
Do you still need that feature?

**Comment by simonepri** [comment]
Implemented in [0.5.0](https://github.com/simonepri/phc-format/releases/tag/v0.5.0)
